#!/bin/bash

progname=$(basename $0)
packagedir=$(dirname $0)
template=${packagedir}/Template.md
tmpdir=/tmp/nesi-makedoc1

# Ensure that some environment variables are set
if [ -z "${NESIDOC_INFO_DIR}" ]
then
	echo "$progname: error: the environment variable \$NESIDOC_INFO_DIR is not set"
	exit 1
elif [ ! -d "${NESIDOC_INFO_DIR}" ]
then
	echo "$progname: ${NESIDOC_INFO_DIR}: not a directory"
	exit 1
fi

if [ -z "${NESIDOC_VERSIONS_DIR}" ]
then
	echo "$progname: error: the environment variable \$NESIDOC_VERSIONS_DIR is not set"
	exit 1
elif [ ! -d "${NESIDOC_VERSIONS_DIR}" ]
then
	echo "$progname: ${NESIDOC_VERSIONS_DIR}: not a directory"
	exit 1
fi

if [ -z "${NESIDOC_MODULELISTS_DIR}" ]
then
	echo "$progname: error: the environment variable \$NESIDOC_MODULELISTS_DIR is not set"
	exit 1
elif [ ! -d "${NESIDOC_MODULELISTS_DIR}" ]
then
	echo "$progname: ${NESIDOC_MODULELISTS_DIR}: not a directory"
	exit 1
fi

# Test for the existence of a lockfile.
# Create one if it is absent.
mkdir -p ${tmpdir}
lockfile=${tmpdir}/lockfile
if [ -e "${lockfile}" ]
then
	echo "$progname: error: ${lockfile} exists."
	echo "Check to make sure that no other instance of $progname is running."
	echo "If necessary, remove ${lockfile} or ask an administrator to do so."
	exit 1
else
	touch ${lockfile}
fi

for dir in versions blurbs
do
	rm -r ${tmpdir}/${dir}
	mkdir -p ${tmpdir}/${dir}
	if [ $? -ne 0 ]
	then
		exit 1
	fi
done

for file in ${NESIDOC_MODULELISTS_DIR}/*
do
	# Get a machine name (the file name minus the extension)
	basefile=$(basename $file)
	machine=${basefile%.*}
	while read line
	do
		module=$(echo $line | cut -d':' -f 1 | \
			sed -e 's/^\s\+//' | sed -e 's/\s\+$//')
		description=$(echo $line | cut -d':' -f 2- | \
			sed -e 's/^\s\+//' | sed -e 's/\s\+$//')
		packagename=$(echo $module | cut -d'/' -f 1 | \
			sed -e 's/^\s\+//' | sed -e 's/\s\+$//')
		version=$(echo $module | cut -d'/' -f 2- | \
			sed -e 's/^\s\+//' | sed -e 's/\s\+$//')

		tempversionfile="${tmpdir}/versions/${packagename}.html"
		if [ ! -e "${tempversionfile}" ]
		then
			echo "<table>" > ${tempversionfile}
			echo "  <tr>" >> ${tempversionfile}
			echo "    <th>Module</th>" >> ${tempversionfile}
			echo "    <th>NeSI Cluster</th>" >> ${tempversionfile}
			echo "  </tr>" >> ${tempversionfile}
		fi
		echo "  <tr>" >> ${tempversionfile}
		echo "    <td>${module}</td>" >> ${tempversionfile}
		echo "    <td>${machine}</td>" >> ${tempversionfile}
		echo "  </tr>" >> ${tempversionfile}

		tempblurbfile="${tmpdir}/blurbs/${packagename}.md"
		echo "## ${module} on ${machine}" >> ${tempblurbfile}
		echo "" >> ${tempblurbfile}
		(echo "${description}" | fold -w 80 -s) >> ${tempblurbfile}
	done < <(sort -u -k1,1 -t ':' $file)
done

for tempversionfile in ${tmpdir}/versions/*
do
	basefile=$(basename $tempversionfile)
	packagename=${basefile%.*}
	echo "</table>" >> ${tempversionfile}
	permversionfile=${NESIDOC_VERSIONS_DIR}/${packagename}.html
	if [ ! -e "${permversionfile}" ]
	then
		echo "Creating a new table of available versions for ${packagename}"
	else
		diff ${tempversionfile} ${permversionfile}
		diffstatus=$?
		if [ ${diffstatus} -eq 2 ]
		then
			echo "$progname: error: comparison of ${tempversionfile} and ${permversionfile} failed"
			continue
		elif [ ${diffstatus} -eq 1 ]
		then
			echo "Available versions of ${packagename} have changed and will be updated."
		fi
	fi
	mv ${tempversionfile} ${permversionfile}
done

for tempblurbfile in ${tmpdir}/blurbs/*
do
	basefile=$(basename $tempblurbfile)
	packagename=${basefile%.*}
	perminfofile=${NESIDOC_INFO_DIR}/${packagename}.md
	if [ ! -e ${perminfofile} ]
	then
		echo "Creating a new information file for $packagename"
		awk -v f="${tempblurbfile}" 'BEGIN {while (getline < f) txt=txt $0 "\n"} /<!--This is a placeholder for a description. Do not edit.-->/ {sub("<!--This is a placeholder for a description. Do not edit.-->", txt)} 1' ${template} > ${perminfofile}
	fi
done

for dir in versions blurbs
do
	rm -r ${tmpdir}/${dir}
done
rm ${lockfile}
